# Generated by Django 5.0.14 on 2026-07-15 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Candidate',
            fields=[
                ('candidate_id', models.IntegerField(primary_key=True, serialize=False)),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=50)),
                ('qualification', models.CharField(max_length=255)),
                ('skills', models.CharField(max_length=500)),
                ('experience', models.IntegerField(default=0)),
                ('password', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Employer',
            fields=[
                ('employer_id', models.IntegerField(primary_key=True, serialize=False)),
                ('company_name', models.CharField(max_length=255)),
                ('hr_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=50)),
                ('location', models.CharField(max_length=255)),
                ('industry', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Interview',
            fields=[
                ('interview_id', models.IntegerField(primary_key=True, serialize=False)),
                ('candidate_name', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('interview_date', models.CharField(max_length=50)),
                ('interview_time', models.CharField(max_length=50)),
                ('interview_mode', models.CharField(max_length=50)),
                ('interview_status', models.CharField(default='Scheduled', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('job_id', models.IntegerField(primary_key=True, serialize=False)),
                ('job_title', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('job_type', models.CharField(max_length=50)),
                ('experience_required', models.IntegerField(default=0)),
                ('salary', models.IntegerField(default=0)),
                ('last_date', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='JobApplication',
            fields=[
                ('application_id', models.IntegerField(primary_key=True, serialize=False)),
                ('candidate_name', models.CharField(max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('job_title', models.CharField(max_length=255)),
                ('applied_date', models.CharField(max_length=50)),
                ('resume', models.CharField(max_length=255)),
                ('application_status', models.CharField(default='Applied', max_length=100)),
            ],
        ),
    ]
